{% set version = "1.6" %}

package:
  name: otsubsetinverse
  version: {{ version }}

source:
  fn: otsubsetinverse-{{ version }}.tar.gz
  url: https://github.com/openturns/otsubsetinverse/archive/v{{ version }}.tar.gz
  sha256: db4357c6d33e8c1c37bb9d8c25bfdedeebf56f269ef5f1abbfdf0546a1fa7fca

build:
  number: 1
  run_exports:
    - {{ pin_subpackage('otsubsetinverse', max_pin='x.x') }}

requirements:
  build:
    - cmake
    - swig
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - openturns 1.15*
  run:
    - python
    - openturns 1.15*

test:
  imports:
    - otsubsetinverse

about:
  home: http://openturns.org/
  license: LGPL-3.0-or-later
  license_family: LGPL
  license_file: COPYING.LESSER
  summary: Inverse subset simulation

extra:
  recipe-maintainers:
    - adumasphi
    - jschueller
