{% set version = "1.2" %}
{% set ot_version = "1.12rc1" %}

package:
  name: otsubsetinverse
  version: {{ version }}

source:
  fn: otsubsetinverse-{{ version }}.tar.gz  # [not win]
  url: https://github.com/openturns/otsubsetinverse/archive/v{{ version }}.tar.gz  # [not win]
  sha256: 8907b5ceda7d36e3ef7ac1f4b9e16a7e9e1fb6cc76d7794bf41ef7170127a91a  # [not win]

  fn: otsubsetinverse-{{ version }}-py2.7-x86_64.exe  # [win64 and py27]
  url: https://github.com/openturns/build-modules/releases/download/v{{ ot_version }}/otsubsetinverse-{{ version }}-py2.7-x86_64.exe  # [win64 and py27]
  sha256: b21fb043a4bfb5548c9bdf45c0e2943b10887104beac0f119c6547c4e7670d80  # [win64 and py27]

  fn: otsubsetinverse-{{ version }}-py3.5-x86_64.exe  # [win64 and py35]
  url: https://github.com/openturns/build-modules/releases/download/v{{ ot_version }}/otsubsetinverse-{{ version }}-py3.5-x86_64.exe  # [win64 and py35]
  sha256: 54d023a7ade6723749623e5fcf1e356b234a7576b22b2077273e9173405d00f6  # [win64 and py35]

  fn: otsubsetinverse-{{ version }}-py3.6-x86_64.exe  # [win64 and py36]
  url: https://github.com/openturns/build-modules/releases/download/v{{ ot_version }}/otsubsetinverse-{{ version }}-py3.6-x86_64.exe  # [win64 and py36]
  sha256: 3b5bf73ed079d6f481dd73a176f378dfc2444273d82becda55bd07bca25ae5c9  # [win64 and py36]

build:
  number: 0
  # not built yet on windows
  skip: true  # [win]

requirements:
  build:
    - cmake  # [not win]
    - {{ compiler('c') }}  # [not win]
    - {{ compiler('cxx') }}  # [not win]
  host:
    - python
    - swig  # [not win]
    - openturns  # [not win]
    - tbb-devel  # [not win]
  run:
    - python
    - openturns

test:
  imports:
    - otsubsetinverse

about:
  home: http://openturns.org/
  license: LGPL3
  license_file: COPYING.LESSER  # [not win]
  summary: Inverse subset simulation

extra:
  recipe-maintainers:
    - adumasphi
    - jschueller
