{% set version = "1.4" %}

package:
  name: otsubsetinverse
  version: {{ version }}

source:
  fn: otsubsetinverse-{{ version }}.tar.gz
  url: https://github.com/openturns/otsubsetinverse/archive/v{{ version }}.tar.gz
  sha256: c03fdf06c583d23d1706f7a6ebd3a771c9fe9b28894258b1ac010ec54e856cec

build:
  number: 0

requirements:
  build:
    - cmake  # [not win]
    - {{ compiler('c') }}  # [not win]
    - {{ compiler('cxx') }}  # [not win]
  host:
    - python
    - swig  # [not win]
    - openturns
  run:
    - python
    - openturns

test:
  imports:
    - otsubsetinverse

about:
  home: http://openturns.org/
  license: LGPL3
  license_file: COPYING.LESSER
  summary: Inverse subset simulation

extra:
  recipe-maintainers:
    - adumasphi
    - jschueller
