{% set version = "1.9" %}

package:
  name: otsubsetinverse
  version: {{ version }}

source:
  fn: otsubsetinverse-{{ version }}.tar.gz
  url: https://github.com/openturns/otsubsetinverse/archive/v{{ version }}.tar.gz
  sha256: b7ec9b4b23d73b411ac55b0dad92b86c45c2618d9157dd9ef7cc53b1d106e97d

build:
  number: 0
  run_exports:
    - {{ pin_subpackage('otsubsetinverse', max_pin='x.x') }}

requirements:
  build:
    - cmake
    - swig
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - curl  # [win]
  host:
    - python
    - openturns 1.18*
  run:
    - python
    - openturns 1.18*

test:
  imports:
    - otsubsetinverse

about:
  home: http://openturns.org/
  license: LGPL-3.0-or-later
  license_family: LGPL
  license_file: COPYING.LESSER
  summary: Inverse subset simulation

extra:
  recipe-maintainers:
    - adumasphi
    - jschueller
