{% set version = "1.10" %}

package:
  name: otsubsetinverse
  version: {{ version }}

source:
  fn: otsubsetinverse-{{ version }}.tar.gz
  url: https://github.com/openturns/otsubsetinverse/archive/v{{ version }}.tar.gz
  sha256: ac1a15373e02d7496979e17f64998a9c1e711c9e29f2b91ace01e59c589ed077

build:
  number: 1
  run_exports:
    - {{ pin_subpackage('otsubsetinverse', max_pin='x.x') }}

requirements:
  build:
    - cmake
    - make  # [unix]
    - swig
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - curl  # [win]
  host:
    - python
    - openturns 1.21*
  run:
    - python
    - openturns 1.21*

test:
  imports:
    - otsubsetinverse

about:
  home: http://openturns.org/
  license: LGPL-3.0-or-later
  license_family: LGPL
  license_file: COPYING.LESSER
  summary: Inverse subset simulation

extra:
  recipe-maintainers:
    - adumasphi
    - jschueller
