appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: wz2FfTPg4EDCJOYtyvYQAX6Hja2jfuRsxr0I2Dh8jeHH0WtG/uUFpo+vyGxSNDNXqoWJbT1HQc7WikjR2QbNNAqGo5teEr3vYnd9o0dsaWX4Ja5XX0MIOI4rWGJHyr8GCz54Do3AhQxwCgRj8y+b7M+AMekV1volXbFM6XALunrL7X4gxZ06/JhJGfWomG72H7wFSJwQ1W1jLbnrn270cUC5sU/gas/jjpDXY7fmp/9VTBWb5t8YcTszrVgSbF6LoPvITXPf5+AVg+puN56EDzixa28GphI2veOW9nMU2mHm1bisrPxdpMmNC92FM38g7Lr5P8jc1iW+Z28ybbZQzMUVFG5BqO8OUTXFabKFr97+4auLyvbwxJe0u11jxPDd0Do1Sq3RGVRzAZ5uGo5UjuSLsqXUtOQ8DHejn3Oo5JTcLuXvy7300EJJbb+uYkJ1TdzBXVDC9xZiGn4/kBt/UYY1TfaIvxzYKm8vpkJdzHLRvvUDgwEtOfRBgpulk7LSSWNDLiQHG+AGTjBp5fBT+wzET9jIEmuSvksjhN/Uub1JnFQ5KtYcap+d7bS3gB1nJMKGoytx61XeaSkmZXkbf7rNi5Hj7o9y2pwtMbcVzy9CYR8SCqWsKSt/RPE/zMXoEv4EcpGXR3sx27ZaUq1/Jgs75M/ABhxl6NV8WJcGG0M=}
provider:
  win: azure
